---
- name: Configuration server for app
  hosts: all
  become: true

  tasks:
    - name: Install Docker
      dnf:
        name: docker
        state: present
        update_only: no
        
    - name: Start docker 
      systemd:
        name: docker
        enabled: yes 
        state: started 

    - name: Add ec2-user to docker group
      user: 
        name: ec2-user 
        groups: docker
        append: yes

    - name: Ensure docker cli-plugins directory exists
      file:
        path: /usr/local/lib/docker/cli-plugins
        state: directory
        mode: "0755"

    - name: Install docker compose plugin
      get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-{{ ansible_architecture }}"
        dest: /usr/local/lib/docker/cli-plugins/docker-compose
        mode: "0755"
        force: no